# Generated by Django 4.0.1 on 2022-01-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbNOTAFISCAL',
            fields=[
                ('idNFE', models.IntegerField(primary_key=True, serialize=False)),
                ('cdServico', models.CharField(max_length=150)),
                ('cdTributacao', models.CharField(max_length=150)),
                ('dsDiscriminacao', models.CharField(max_length=150)),
                ('cdCNAE', models.CharField(max_length=150)),
                ('vrServico', models.FloatField()),
                ('vrLiquido', models.FloatField()),
                ('cdCNPJPrestador', models.CharField(max_length=255)),
                ('cdCPFTomador', models.CharField(max_length=255)),
                ('cdCEPTomador', models.CharField(max_length=150)),
                ('dsTipoLogradouroTomador', models.CharField(max_length=50)),
                ('dsEnderecoTomador', models.CharField(max_length=255)),
                ('dsTipoBairroTomador', models.CharField(max_length=100)),
                ('cdCidadeTomador', models.CharField(max_length=150)),
                ('sgEstadoTomador', models.CharField(max_length=50)),
                ('nrEnderecoTomador', models.IntegerField()),
                ('dsBairroTomador', models.CharField(max_length=150)),
            ],
        ),
    ]
