# Generated by Django 4.0.1 on 2022-01-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbnotafiscal',
            name='cdCNAE',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
