# Generated by Django 4.0.1 on 2022-01-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tbnotafiscal_cdcnae'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbnotafiscal',
            name='urlPDF',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tbnotafiscal',
            name='urlXML',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
