# Generated by Django 4.0.1 on 2022-01-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tbnotafiscal_dsstatus_tbnotafiscal_dtemissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbNOTAFISCALERRO',
            fields=[
                ('idErro', models.IntegerField(primary_key=True, serialize=False)),
                ('idNFE', models.IntegerField()),
                ('dsErro', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='tbnotafiscal',
            name='flErro',
            field=models.BinaryField(null=True),
        ),
    ]
