# Generated by Django 4.0.1 on 2022-01-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tbnotafiscalerro_tbnotafiscal_flerro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbnotafiscal',
            options={'verbose_name': 'Nota Fiscal', 'verbose_name_plural': 'Notas Fiscais'},
        ),
        migrations.AddField(
            model_name='tbnotafiscal',
            name='idRetorno',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbnotafiscal',
            name='cdCEPTomador',
            field=models.CharField(max_length=150, verbose_name='CEP do Tomador'),
        ),
        migrations.AlterField(
            model_name='tbnotafiscal',
            name='cdCNAE',
            field=models.CharField(blank=True, max_length=150, verbose_name='Código CNAE'),
        ),
        migrations.AlterField(
            model_name='tbnotafiscal',
            name='cdCNPJPrestador',
            field=models.CharField(max_length=255, verbose_name='CNPJ do Prestador'),
        ),
        migrations.AlterField(
            model_name='tbnotafiscal',
            name='cdCPFTomador',
            field=models.CharField(max_length=255, verbose_name='CPF do Tomador'),
        ),
        migrations.AlterField(
            model_name='tbnotafiscal',
            name='cdCidadeTomador',
            field=models.CharField(max_length=150, verbose_name='Cidade do Tomador'),
        ),
        migrations.AlterField(
            model_name='tbnotafiscal',
            name='cdServico',
            field=models.CharField(max_length=150, verbose_name='Código de Serviço'),
        ),
        migrations.AlterField(
            model_name='tbnotafiscal',
            name='cdTributacao',
            field=models.CharField(blank=True, max_length=150, verbose_name='Código de Tributação'),
        ),
        migrations.AlterField(
            model_name='tbnotafiscal',
            name='dsBairroTomador',
            field=models.CharField(max_length=150, verbose_name='Bairro do Tomador'),
        ),
        migrations.AlterField(
            model_name='tbnotafiscal',
            name='dsEnderecoTomador',
            field=models.CharField(max_length=255, verbose_name='Endereço do Tomador'),
        ),
        migrations.AlterField(
            model_name='tbnotafiscal',
            name='dsTipoBairroTomador',
            field=models.CharField(max_length=100, verbose_name='Tipo do bairro do Tomador'),
        ),
        migrations.AlterField(
            model_name='tbnotafiscal',
            name='dsTipoLogradouroTomador',
            field=models.CharField(max_length=50, verbose_name='Tipo logradouro do Tomador'),
        ),
        migrations.AlterField(
            model_name='tbnotafiscal',
            name='nrEnderecoTomador',
            field=models.IntegerField(verbose_name='Número do endereço do Tomador'),
        ),
        migrations.AlterField(
            model_name='tbnotafiscal',
            name='sgEstadoTomador',
            field=models.CharField(max_length=50, verbose_name='Estado do Tomador'),
        ),
        migrations.AlterField(
            model_name='tbnotafiscal',
            name='vrLiquido',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor líquido do Serviço'),
        ),
        migrations.AlterField(
            model_name='tbnotafiscal',
            name='vrServico',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do Serviço'),
        ),
    ]
