# Generated by Django 4.0.1 on 2022-01-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tbnotafiscal_options_tbnotafiscal_idretorno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbnotafiscal',
            name='vrLiquido',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor líquido do Serviço'),
        ),
        migrations.AlterField(
            model_name='tbnotafiscal',
            name='vrServico',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor do Serviço'),
        ),
    ]
