# Generated by Django 4.0.1 on 2022-01-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_tbnotafiscal_vrliquido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='teste',
            fields=[
                ('idNFE', models.IntegerField(primary_key=True, serialize=False)),
                ('ds', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
