# Generated by Django 4.0.1 on 2022-01-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbnotafiscal',
            name='nmTomador',
            field=models.CharField(max_length=150, null=True, verbose_name='Nome do Tomador'),
        ),
    ]
