# Generated by Django 4.0.1 on 2022-01-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tbnotafiscal_nmtomador'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='testeDs',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
