# Generated by Django 4.0.1 on 2022-01-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_teste_testeds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teste',
        ),
    ]
