# Generated by Django 4.0.1 on 2022-01-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_tbnotafiscal_vrliquido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbnotafiscal',
            name='idNFE',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='chave'),
        ),
    ]
